# Feature Engineering

- So far we have performed feature analysis
    - Data frame quick checks
    - categorical column analysis
    - Bar charts, pie Charts
    - Numerical column alanysis
    - Histogram, Box plots, outliers
    - Bi-multi variate analysis
    - correlation etc
- Now we need to learn Feature Enginnering
    - we will create a new columns for better ML models
    - we will perform the **Encoding**, which is convert categorical to Numerical data
    - we will do data **transformations**
    - we will perform **Scaling: Standaization and Normalization**
    - We will perform the **missing value analysis**
- Simply feature engineering means our data will be modified

- Feature Analysis
- Feature Engineering
- Feature Selection
- Model Development
- Model Evaluation -> testing performance
- Model tuniing
- Model Deployment

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
file_path=r"C:\Users\learn\Documents\NareshIT\EDA\Pandas\Visadataset - Visadataset.csv"
visa_df = pd.read_csv(file_path)
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [3]:
cat=visa_df.select_dtypes(include='object').columns
num=visa_df.select_dtypes(exclude='object').columns

**Encoding**

- Encoding means convert categorical data to numerical data
- Ml/DL or any models works based on maths
- Models cannot understand English  charcters
- So it is very important convert categorical label to numerical values
- For example Gender Colun has two labels:
    - Male
    - Female
- then Female represent as 0, Male represnt 1 based on alphabetical order

In [4]:
case_status_keys=visa_df['case_status'].value_counts().keys()
case_status_values=visa_df['case_status'].value_counts().values

In [5]:
len(case_status_keys)

2

In [6]:
case_status_keys

Index(['Certified', 'Denied'], dtype='object', name='case_status')

In [7]:
case_status_values

array([17018,  8462], dtype=int64)

In [8]:
visa_df['case_status'].unique()

array(['Denied', 'Certified'], dtype=object)

- Certified should assign as 0
- Denied should assign as 1

In [10]:
# Mapping
d = {'Certified':0,'Denied':1} 
d

{'Certified': 0, 'Denied': 1}

In [11]:
visa_df['case_status']

0           Denied
1        Certified
2           Denied
3           Denied
4        Certified
           ...
25475    Certified
25476    Certified
25477    Certified
25478    Certified
25479    Certified
Name: case_status, Length: 25480, dtype: object

In [12]:
visa_df['case_status'].map(d)

0        1
1        0
2        1
3        1
4        0
        ..
25475    0
25476    0
25477    0
25478    0
25479    0
Name: case_status, Length: 25480, dtype: int64

In [13]:
# If you geting NaN you ran double time so do one by one from statring means read the data, Select the column, create a mapper, map too selected column
visa_df['case_status'] = visa_df['case_status'].map(d) # Upadating exsting daata

In [14]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [16]:
visa_df['continent'].unique()

array(['Asia', 'Africa', 'North America', 'Europe', 'South America',
       'Oceania'], dtype=object)

In [ ]:
d = {'Asia':0, 'Africa', 'North America', 'Europe', 'South America',
       'Oceania'} # dont like this

In [23]:
j=0
d = {}
for i in sorted(visa_df['continent'].unique()):
    d[i] = j
    j=j+1
d

{'Africa': 0,
 'Asia': 1,
 'Europe': 2,
 'North America': 3,
 'Oceania': 4,
 'South America': 5}

In [27]:
# Create a dictionary
d = {}
d['Asia'] = 0
d['Africa'] = 1
d['North America'] = 2
d['Europe'] = 3
d['South America'] = 4
d['Oceania'] = 5
d

{'Asia': 0,
 'Africa': 1,
 'North America': 2,
 'Europe': 3,
 'South America': 4,
 'Oceania': 5}

In [28]:
labels = sorted(visa_df['continent'].unique())
d = {}
for i,j in enumerate(labels):
    d[j]=i
d

{'Africa': 0,
 'Asia': 1,
 'Europe': 2,
 'North America': 3,
 'Oceania': 4,
 'South America': 5}

In [29]:
fruits = ["apple", "banana", "cherry"]

for index, fruit in enumerate(fruits):
    print(index, fruit)

0 apple
1 banana
2 cherry

In [30]:
fruits = ["apple", "banana", "cherry"]
for i in range(len(fruits)):
    print(i, fruits[i])

0 apple
1 banana
2 cherry

In [32]:
labels = sorted(visa_df['continent'].unique())
d = {j:i for i,j in enumerate(labels)}
d

{'Africa': 0,
 'Asia': 1,
 'Europe': 2,
 'North America': 3,
 'Oceania': 4,
 'South America': 5}

In [35]:
visa_df['continent'] = visa_df['continent'].map(d)

In [36]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status,continentn
0,EZYV01,1,High School,N,N,14513,2007,West,592.2029,Hour,Y,1,1
1,EZYV02,1,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0,1
2,EZYV03,1,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1,1
3,EZYV04,1,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1,1
4,EZYV05,0,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0,1
25476,EZYV25477,1,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0,1
25477,EZYV25478,1,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0,1
25478,EZYV25479,1,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0,1
25479,EZYV25480,1,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0,1

In [37]:
# i need to repeat abbove 3 lines for all cat column
# except case_id

In [43]:
file_path=r"C:\Users\learn\Documents\NareshIT\EDA\Pandas\Visadataset - Visadataset.csv"
visa_df = pd.read_csv(file_path)
cat=visa_df.select_dtypes(include='object').columns
for i in cat[1:]:
    labels = sorted(visa_df[i].unique())
    d = {j:i for i,j in enumerate(labels)}
    visa_df[i] = visa_df[i].map(d)

In [44]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,2,0,0,14513,2007,4,592.2029,0,1,1
1,EZYV02,1,3,1,0,2412,2002,2,83425.6500,3,1,0
2,EZYV03,1,0,0,1,44444,2008,4,122996.8600,3,1,1
3,EZYV04,1,0,0,0,98,1897,4,83434.0300,3,1,1
4,EZYV05,0,3,1,0,1082,2005,3,149907.3900,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,0,1,1,2601,2008,3,77092.5700,3,1,0
25476,EZYV25477,1,2,1,0,3274,2006,2,279174.7900,3,1,0
25477,EZYV25478,1,3,1,0,1121,1910,3,146298.8500,3,0,0
25478,EZYV25479,1,3,1,1,1918,1887,4,86154.7700,3,1,0
25479,EZYV25480,1,0,1,0,3195,1960,1,70876.9100,3,1,0

# LabelEncoder

- LabelEncoder is a method will convert cat labels to numerical values
- It is under package: **sklearn (sickit-learn)**
    - the class name: **preprocessing**
        - The method name: **LabelEncoder**

In [45]:
# from <package>.<class> import <method>

In [46]:
from sklearn.preprocessing import LabelEncoder

- Step-1: we need to import the method
- Step-2: save the method
- Step-3:apply fit transform

- **fit transform**
    - **fit**: means find the logic
        - in above example fit means create **mapper** or **dict**
    - **transform**: apply the logic and change the data
        - apply the **mapper on the data**

In [48]:
# read the data again 
file_path=r"C:\Users\learn\Documents\NareshIT\EDA\Pandas\Visadataset - Visadataset.csv"
visa_df = pd.read_csv(file_path)
cat=visa_df.select_dtypes(include='object').columns

# Import the method
from sklearn.preprocessing import LabelEncoder

# Save the method
le = LabelEncoder()

# apply fit transform
le.fit_transform(visa_df['case_status'])

array([1, 0, 1, ..., 0, 0, 0])

In [49]:
# read the data again 
file_path=r"C:\Users\learn\Documents\NareshIT\EDA\Pandas\Visadataset - Visadataset.csv"
visa_df = pd.read_csv(file_path)
cat=visa_df.select_dtypes(include='object').columns

# Import the method
from sklearn.preprocessing import LabelEncoder

# Save the method
le = LabelEncoder()

# apply fit transform
visa_df['case_status'] = le.fit_transform(visa_df['case_status'])
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [51]:
# read the data
file_path=r"C:\Users\learn\Documents\NareshIT\EDA\Pandas\Visadataset - Visadataset.csv"
visa_df = pd.read_csv(file_path)
cat=visa_df.select_dtypes(include='object').columns

# Import the method
from sklearn.preprocessing import LabelEncoder

# Save the method
le = LabelEncoder()

# apply fit transform
visa_df['continent'] = le.fit_transform(visa_df['continent'])
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,1,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,1,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,1,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,0,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,1,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,1,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,1,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,1,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [54]:
# read the data
file_path=r"C:\Users\learn\Documents\NareshIT\EDA\Pandas\Visadataset - Visadataset.csv"
visa_df = pd.read_csv(file_path)
cat=visa_df.select_dtypes(include='object').columns

# Import the method
from sklearn.preprocessing import LabelEncoder

# Save the method
le = LabelEncoder()

# apply fit transform with for loop means all categorical columns
for i in cat[1:]:
    labels = sorted(visa_df[i].unique())
    visa_df[i] = le.fit_transform(visa_df[i])
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,2,0,0,14513,2007,4,592.2029,0,1,1
1,EZYV02,1,3,1,0,2412,2002,2,83425.6500,3,1,0
2,EZYV03,1,0,0,1,44444,2008,4,122996.8600,3,1,1
3,EZYV04,1,0,0,0,98,1897,4,83434.0300,3,1,1
4,EZYV05,0,3,1,0,1082,2005,3,149907.3900,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,0,1,1,2601,2008,3,77092.5700,3,1,0
25476,EZYV25477,1,2,1,0,3274,2006,2,279174.7900,3,1,0
25477,EZYV25478,1,3,1,0,1121,1910,3,146298.8500,3,0,0
25478,EZYV25479,1,3,1,1,1918,1887,4,86154.7700,3,1,0
25479,EZYV25480,1,0,1,0,3195,1960,1,70876.9100,3,1,0

## OneHotEncoder

- First how many lables are there in a columns
- that many new columns will be created extra
- for example case status has two lables
    - certified
    - Denied
- So it will create two new extra columns
    - case_status_Certified
    - case_status_Denied
- At a time one column value become 1 other column value become 0
- This means a **OneHotEncoder**
  
|case_status|case_status_Certified|case_status_Denied|
|-|-|-|
|Certified|1|0
|Denied|0|1
|Denied|0|1
|Certified|1|0

In [55]:
# Continent  C_A   C_AF    C_E
# Asis       1      0       0
# Africa     0      1       0
# Europe     0      0       1

**pd.get_dummies**

In [56]:
# read the data
file_path=r"C:\Users\learn\Documents\NareshIT\EDA\Pandas\Visadataset - Visadataset.csv"
visa_df = pd.read_csv(file_path)
cat=visa_df.select_dtypes(include='object').columns

pd.get_dummies(visa_df['case_status'])

       Certified  Denied
0          False    True
1           True   False
2          False    True
3          False    True
4           True   False
...          ...     ...
25475       True   False
25476       True   False
25477       True   False
25478       True   False
25479       True   False

[25480 rows x 2 columns]

In [57]:
# read the data
file_path=r"C:\Users\learn\Documents\NareshIT\EDA\Pandas\Visadataset - Visadataset.csv"
visa_df = pd.read_csv(file_path)
cat=visa_df.select_dtypes(include='object').columns

pd.get_dummies(visa_df['case_status'], dtype=int)

       Certified  Denied
0              0       1
1              1       0
2              0       1
3              0       1
4              1       0
...          ...     ...
25475          1       0
25476          1       0
25477          1       0
25478          1       0
25479          1       0

[25480 rows x 2 columns]

In [58]:
# read the data
file_path=r"C:\Users\learn\Documents\NareshIT\EDA\Pandas\Visadataset - Visadataset.csv"
visa_df = pd.read_csv(file_path)
cat=visa_df.select_dtypes(include='object').columns

pd.get_dummies(visa_df['continent'])

       Africa   Asia  Europe  North America  Oceania  South America
0       False   True   False          False    False          False
1       False   True   False          False    False          False
2       False   True   False          False    False          False
3       False   True   False          False    False          False
4        True  False   False          False    False          False
...       ...    ...     ...            ...      ...            ...
25475   False   True   False          False    False          False
25476   False   True   False          False    False          False
25477   False   True   False          False    False          False
25478   False   True   False          False    False          False
25479   False   True   False          False    False          False

[25480 rows x 6 columns]

In [59]:
# read the data
file_path=r"C:\Users\learn\Documents\NareshIT\EDA\Pandas\Visadataset - Visadataset.csv"
visa_df = pd.read_csv(file_path)
cat=visa_df.select_dtypes(include='object').columns

pd.get_dummies(visa_df['continent'],dtype=int)

       Africa  Asia  Europe  North America  Oceania  South America
0           0     1       0              0        0              0
1           0     1       0              0        0              0
2           0     1       0              0        0              0
3           0     1       0              0        0              0
4           1     0       0              0        0              0
...       ...   ...     ...            ...      ...            ...
25475       0     1       0              0        0              0
25476       0     1       0              0        0              0
25477       0     1       0              0        0              0
25478       0     1       0              0        0              0
25479       0     1       0              0        0              0

[25480 rows x 6 columns]